### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by ThomasBourgeois** [danidee10/Votr#9]
There's something wrong. Check what I had using directly your app on heroku : https://user-images.githubusercontent.com/11358792/35193617-7a38b104-fea5-11e7-8eec-806be469fcf4.png)

**Comment by danidee10** [comment]
Thanks for reporting. I'll check it out

**Comment by danidee10** [comment]
@ThomasBourgeois this issue has been fixed in https://github.com/danidee10/Votr/commit/08b2eaa751dd00a3fda7fd77947bc121714e5f77

This was the culprit:
`status = db.Column(db.Boolean, default=1)  # to mark poll as open or closed`

Specifically `default=1`

Locally when using `SQLite` This code would work because `SQLite` stores boolean fields as Integers (It doesn't actually have a `Boolean` field). 

In production with `PostgreSQL` it failed because postgres stores booleans as bytes. (1 byte to be precise). 

The solution was to set it to `True`

`status = db.Column(db.Boolean, default=True)  # to mark poll as open or closed`

`SQLAlchemy` would take care of converting it to the right property so it's still cross-platform and works on both `SQLite` and `PostgreSQL`.

**Comment by ThomasBourgeois** [comment]
Thx!
